### ISSUE TITLE
Namespace for skosno er feil

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/skos-ap-no-tools#13]
Namespace er satt til http://difi.no/skosno# Dette namespacet fins ikkje lenger, så dette må endrast til gjeldande namespace https://data.norge.no/vocabulary/skosno#

**Comment by lillelars** [comment]
bruker skos-ap-no-tools ? @stigbd 
Fungerer det ikek som det skal?

**Comment by stigbd** [comment]
Dette _er_ skos-ap-no tools. Det kan sjå ut som at @NilsOveTen har rett i at skosno namespace er korrekt. Så derfor er det brreg som brukar ein gammal versjon. Det er litt uoversiktlig at the moment. Vi bør rydde opp i brancher og andre feil (feil dcatno namespace), men det er for så vidt utanfor scope i dette issuet.

**Comment by NilsOveTen** [comment]
Ble fikset av https://github.com/Informasjonsforvaltning/skos-ap-no-tools/issues/9
