### ISSUE TITLE
[concept-builder] Legge til coverage

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/skos-ap-no-tools#19]
Legg til coverage slik at vi kan få opp metrikker rundt endring i coverage i PRs.

**Comment by KjerstiSteien** [comment]
@jimjyang @KurtStian Skjønner dere hva dette skulle løse, og tror dere det er relevant lenger?

**Comment by jimjyang** [comment]
> @jimjyang @KurtStian Skjønner dere hva dette skulle løse, og tror dere det er relevant lenger?

nei, dessverre.

**Comment by stigbd** [comment]
Trur det var tenkt som test-coverage, altså ein metric for kor mykje av kildekoden som er dekka av automatisk test.

**Comment by KjerstiSteien** [comment]
Det høres nyttig ut. @KurtStian kunne du forfulgt den tanken?

**Comment by KjerstiSteien** [comment]
Mer helhetlig, kanskje ikke begrenset til skos-ap-no-tools.
